version: "3"

services:
  kluster:
    image: kluster/ubuntu
    container_name: kluster
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data:/data
    network_mode: host
    #    stdin_open: true
    #tty: true
    #command: /bin/bash
